export const options = [
  {
    value: 'Electronics',
    label: 'Electronics',
    children: [
      {
        value: 'Mobile Phones',
        label: 'Mobile Phones',
        keywords: [
          'Phone',
          'Smartphone',
          'Cell Phone',
          'Mobile',
          'Telephone',
          'Handheld',
          'Screen',
          'Touchscreen',
        ],
      },
      {
        value: 'Laptops & Computers',
        label: 'Laptops & Computers',
        keywords: [
          'Laptop',
          'Computer',
          'Desktop',
          'PC',
          'Macbook',
          'Chromebook',
          'Keyboard',
          'Screen',
        ],
      },
      {
        value: 'Peripherals & Input Devices',
        label: 'Peripherals & Input Devices',
        keywords: [
          'Monitor',
          'Keyboard',
          'Mouse',
          'Printer',
          'Scanner',
          'Touchpad',
          'Joystick',
          'Webcam',
          'Microphone',
        ],
      },
      {
        value: 'Tablets',
        label: 'Tablets',
        keywords: [
          'Tablet',
          'E-reader',
          'iPad',
          'Kindle',
          'Slate',
          'Touchscreen',
        ],
      },
      {
        value: 'TVs & Monitors',
        label: 'TVs & Monitors',
        keywords: [
          'Television',
          'TV',
          'Screen',
          'Display',
          'Projector',
          'LCD',
          'Plasma',
          'Monitor',
        ],
      },
      {
        value: 'Cameras',
        label: 'Cameras',
        keywords: [
          'Camera',
          'Camcorder',
          'Lens',
          'DSLR',
          'SLR',
          'Webcam',
          'Flash',
          'Tripod',
        ],
      },
      {
        value: 'Audio & Headphones',
        label: 'Audio & Headphones',
        keywords: [
          'Headphones',
          'Speaker',
          'Microphone',
          'Stereo',
          'Earbuds',
          'Headset',
          'Amplifier',
          'Subwoofer',
          'Soundbar',
        ],
      },
      {
        value: 'Gaming Consoles',
        label: 'Gaming Consoles',
        keywords: [
          'Console',
          'Controller',
          'Gamepad',
          'PlayStation',
          'Xbox',
          'Nintendo',
          'Joystick',
          'Arcade',
        ],
      },
      {
        value: 'Wearables',
        label: 'Wearables',
        keywords: [
          'Watch',
          'Smartwatch',
          'Tracker',
          'Wristwatch',
          'Pedometer',
          'Band',
        ],
      },
      {
        value: 'Accessories & Cables',
        label: 'Accessories & Cables',
        keywords: [
          'Charger',
          'Adapter',
          'Cable',
          'Bank',
          'Connector',
          'Wire',
          'Plug',
          'USB',
          'Cord',
          'Battery',
        ],
      },
    ],
  },
  {
    value: 'Home & Furniture',
    label: 'Home & Furniture',
    children: [
      {
        value: 'Sofas & Chairs',
        label: 'Sofas & Chairs',
        keywords: [
          'Sofa',
          'Couch',
          'Chair',
          'Stool',
          'Armchair',
          'Recliner',
          'Loveseat',
          'Futon',
          'Seat',
        ],
      },
      {
        value: 'Tables & Desks',
        label: 'Tables & Desks',
        keywords: ['Table', 'Desk', 'Workstation', 'Counter', 'Stand'],
      },
      {
        value: 'Beds & Mattresses',
        label: 'Beds & Mattresses',
        keywords: [
          'Bed',
          'Mattress',
          'Crib',
          'Cot',
          'Bunk',
          'Headboard',
          'Frame',
          'Bedding',
        ],
      },
      {
        value: 'Storage',
        label: 'Storage',
        keywords: [
          'Cabinet',
          'Closet',
          'Dresser',
          'Bookshelf',
          'Shelf',
          'Wardrobe',
          'Cupboard',
          'Drawer',
          'Chest',
        ],
      },
      {
        value: 'Home Decor',
        label: 'Home Decor',
        keywords: [
          'Lamp',
          'Rug',
          'Curtain',
          'Vase',
          'Painting',
          'Mirror',
          'Art',
          'Frame',
          'Clock',
          'Tapestry',
          'Ornament',
          'Cushion',
          'Carpet',
        ],
      },
      {
        value: 'Kitchen Appliances',
        label: 'Kitchen Appliances',
        keywords: [
          'Refrigerator',
          'Oven',
          'Stove',
          'Microwave',
          'Blender',
          'Dishwasher',
          'Toaster',
          'Mixer',
          'Kettle',
          'Fridge',
          'Cooker',
        ],
      },
      {
        value: 'Lighting',
        label: 'Lighting',
        keywords: [
          'Light',
          'Chandelier',
          'Lamp',
          'Bulb',
          'Fixture',
          'Lantern',
          'Sconce',
          'Lampshade',
          'Illumination',
        ],
      },
    ],
  },
  {
    value: 'Vehicles',
    label: 'Vehicles',
    children: [
      {
        value: 'cars',
        label: 'Cars',
        keywords: [
          'Car',
          'Sedan',
          'SUV',
          'Truck',
          'Automobile',
          'Coupe',
          'Hatchback',
          'Convertible',
          'Minivan',
          'Jeep',
          'Pickup',
        ],
      },
      {
        value: 'Caravans & Motorhomes',
        label: 'Caravans & Motorhomes',
        keywords: [
          'RV',
          'Motorhome',
          'Campervan',
          'Caravan',
          'Trailer',
          'Camper',
        ],
      },
      {
        value: 'Motorbikes & Scooters',
        label: 'Motorbikes & Scooters',
        keywords: [
          'Motorcycle',
          'Motorbike',
          'Scooter',
          'Moped',
          'Chopper',
          'Dirt Bike',
        ],
      },
      {
        value: 'Bicycles',
        label: 'Bicycles',
        keywords: ['Bicycle', 'Bike', 'Tricycle', 'BMX', 'Cycling'],
      },
      {
        value: 'Auto Parts & Accessories',
        label: 'Auto Parts & Accessories',
        keywords: [
          'Tire',
          'Wheel',
          'Engine',
          'Headlight',
          'Bumper',
          'Mirror',
          'Seat',
          'Exhaust',
          'Battery',
          'Alloy',
          'Brake',
          'Steering',
        ],
      },
    ],
  },
  {
    value: 'Fashion',
    label: 'Fashion',
    children: [
      {
        value: 'Men’s Clothing',
        label: 'Men’s Clothing',
        keywords: [
          'Shirt',
          'Jeans',
          'Trousers',
          'Jacket',
          'Coat',
          'Suit',
          'T-Shirt',
          'Sweater',
          'Hoodie',
          'Shorts',
          'Tuxedo',
          'Pants',
        ],
      },
      {
        value: 'Women’s Clothing',
        label: 'Women’s Clothing',
        keywords: [
          'Dress',
          'Blouse',
          'Skirt',
          'Jacket',
          'Coat',
          'Top',
          'Gown',
          'Sweater',
          'Hoodie',
          'Leggings',
          'Lingerie',
          'Pants',
        ],
      },
      {
        value: 'Footwear',
        label: 'Footwear',
        keywords: [
          'Shoe',
          'Boot',
          'Sneaker',
          'Sandal',
          'Heel',
          'Slipper',
          'Loafer',
          'Pump',
          'Cleat',
        ],
      },
      {
        value: 'Bags & Luggage',
        label: 'Bags & Luggage',
        keywords: [
          'Bag',
          'Backpack',
          'Handbag',
          'Suitcase',
          'Purse',
          'Tote',
          'Briefcase',
          'Duffel',
          'Wallet',
          'Pack',
        ],
      },
      {
        value: 'Jewelry & Watches',
        label: 'Jewelry & Watches',
        keywords: [
          'Watch',
          'Ring',
          'Necklace',
          'Bracelet',
          'Earring',
          'Pendant',
          'Brooch',
          'Bangle',
          'Diamond',
          'Gold',
          'Silver',
        ],
      },
    ],
  },
  {
    value: 'Books & Education',
    label: 'Books & Education',
    children: [
      {
        value: 'Textbooks',
        label: 'Textbooks',
        keywords: [
          'Book',
          'Manual',
          'Textbook',
          'Workbook',
          'Encyclopedia',
          'Dictionary',
        ],
      },
      {
        value: 'Novels',
        label: 'Novels',
        keywords: [
          'Book',
          'Novel',
          'Paperback',
          'Hardcover',
          'Magazine',
          'Comic',
          'Publication',
        ],
      },
      {
        value: 'Study Tables/Chairs',
        label: 'Study Tables/Chairs',
        keywords: ['Desk', 'Chair', 'Table', 'Workstation'],
      },
      {
        value: 'Stationery',
        label: 'Stationery',
        keywords: [
          'Pen',
          'Pencil',
          'Notebook',
          'Paper',
          'Eraser',
          'Ruler',
          'Marker',
          'Calculator',
          'Stapler',
          'Binder',
        ],
      },
    ],
  },
  {
    value: 'Kids & Toys',
    label: 'Kids & Toys',
    children: [
      {
        value: 'toys-games',
        label: 'Toys & Games',
        keywords: [
          'Toy',
          'Game',
          'Puzzle',
          'Doll',
          'Figure',
          'Blocks',
          'Lego',
          'Plush',
          'Teddy',
          'Board',
        ],
      },
      {
        value: 'Baby Gear',
        label: 'Baby Gear',
        keywords: [
          'Carrier',
          'Seat',
          'Monitor',
          'Pillow',
          'Bouncer',
          'Pacifier',
          'Bottle',
          'Walker',
        ],
      },
      {
        value: 'Kids’ Clothing',
        label: 'Kids’ Clothing',
        keywords: [
          'Shirt',
          'Pants',
          'Onesie',
          'Bib',
          'Romper',
          'Pajamas',
          'Shorts',
        ],
      },
      {
        value: 'Strollers & Cribs',
        label: 'Strollers & Cribs',
        keywords: [
          'Stroller',
          'Pram',
          'Crib',
          'Bed',
          'Playpen',
          'Bassinet',
          'Buggy',
          'Pushchair',
        ],
      },
    ],
  },
  {
    value: 'Art, Crafts & Supplies',
    label: 'Art, Crafts & Supplies',
    children: [
      {
        value: 'Art Supplies',
        label: 'Art Supplies',
        keywords: [
          'Paint',
          'Canvas',
          'Brush',
          'Easel',
          'Palette',
          'Crayon',
          'Sketchbook',
          'Pigment',
          'Marker',
        ],
      },
      {
        value: 'Crafting & Sewing',
        label: 'Crafting & Sewing',
        keywords: [
          'Machine',
          'Fabric',
          'Yarn',
          'Needles',
          'Beads',
          'Thread',
          'Scissors',
          'Pattern',
          'Sewing',
        ],
      },
      {
        value: 'Musical Instruments',
        label: 'Musical Instruments',
        keywords: [
          'Guitar',
          'Piano',
          'Violin',
          'Drum',
          'Flute',
          'Keyboard',
          'Cello',
          'Trumpet',
          'Saxophone',
          'Bass',
          'Synthesizer',
        ],
      },
      {
        value: 'Photography Equipment',
        label: 'Photography Equipment',
        keywords: [
          'Tripod',
          'Lens',
          'Lighting',
          'Flash',
          'Softbox',
          'Backdrop',
          'Stand',
          'Gimbal',
          'Umbrella',
        ],
      },
    ],
  },
  {
    value: 'Wedding & Bridal',
    label: 'Wedding & Bridal',
    children: [
      {
        value: 'wedding-dresses',
        label: 'Wedding Dresses & Wear',
        keywords: ['Dress', 'Gown', 'Veil', 'Tuxedo', 'Tiara', 'Train', 'Suit'],
      },
      {
        value: 'wedding-decor',
        label: 'Wedding Decor & Supplies',
        keywords: [
          'Table',
          'Chair',
          'Lighting',
          'Centerpiece',
          'Floral',
          'Arch',
          'Bouquet',
          'Banner',
        ],
      },
      {
        value: 'wedding-rings',
        label: 'Engagement & Wedding Rings',
        keywords: ['Ring', 'Diamond', 'Band', 'Solitaire'],
      },
    ],
  },
  {
    value: 'Home Improvement & Building Supplies',
    label: 'Home Improvement & Building Supplies',
    children: [
      {
        value: 'building-materials',
        label: 'Building Materials & Supplies',
        keywords: [
          'Lumber',
          'Brick',
          'Cement',
          'Drywall',
          'Concrete',
          'Wood',
          'Plank',
          'Timber',
          'Plywood',
          'Stone',
        ],
      },
      {
        value: 'doors-windows-fittings',
        label: 'Doors, Windows & Fittings',
        keywords: [
          'Door',
          'Window',
          'Frame',
          'Hinge',
          'Lock',
          'Knob',
          'Handle',
          'Glass',
          'Pane',
          'Latch',
        ],
      },
      {
        value: 'plumbing-fixtures',
        label: 'Plumbing & Bathroom Fixtures',
        keywords: [
          'Sink',
          'Toilet',
          'Bathtub',
          'Faucet',
          'Shower',
          'Pipe',
          'Valve',
          'Basin',
          'Tub',
          'Drain',
        ],
      },
      {
        value: 'flooring-tiles',
        label: 'Flooring & Wall Tiles',
        keywords: [
          'Floor',
          'Tile',
          'Porcelain',
          'Ceramic',
          'Marble',
          'Laminate',
          'Carpet',
          'Hardwood',
          'Plank',
        ],
      },
    ],
  },
  {
    value: 'Patio, Garden & Outdoor',
    label: 'Patio, Garden & Outdoor',
    children: [
      {
        value: 'garden-tools',
        label: 'Gardening & Tools',
        keywords: [
          'Mower',
          'Shovel',
          'Rake',
          'Hoe',
          'Trowel',
          'Chainsaw',
          'Trimmer',
          'Wheelbarrow',
          'Shears',
          'Hose',
        ],
      },
      {
        value: 'patio-furniture',
        label: 'Patio & Outdoor Furniture',
        keywords: [
          'Table',
          'Chair',
          'Lounger',
          'Bench',
          'Hammock',
          'Parasol',
          'Umbrella',
        ],
      },
      {
        value: 'bbq-grill',
        label: 'BBQs & Grills',
        keywords: [
          'Barbecue',
          'Grill',
          'Smoker',
          'Charcoal',
          'Roaster',
          'Spit',
        ],
      },
      {
        value: 'plants-seeds',
        label: 'Plants, Seeds & Pots',
        keywords: [
          'Plant',
          'Tree',
          'Flower',
          'Pot',
          'Shrub',
          'Grass',
          'Seedling',
          'Planter',
          'Succulent',
          'Fern',
        ],
      },
    ],
  },
  {
    value: 'Health & Medical Equipment',
    label: 'Health & Medical Equipment',
    children: [
      {
        value: 'Fitness & Exercise',
        label: 'Fitness & Exercise',
        keywords: [
          'Treadmill',
          'Bike',
          'Dumbbell',
          'Mat',
          'Weights',
          'Barbell',
          'Kettlebell',
          'Elliptical',
          'Bench',
          'Gym',
        ],
      },
      {
        value: 'Personal Care & Beauty',
        label: 'Personal Care & Beauty',
        keywords: [
          'Dryer',
          'Shaver',
          'Toothbrush',
          'Makeup',
          'Cosmetics',
          'Clipper',
          'Razor',
          'Lipstick',
          'Perfume',
          'Brush',
        ],
      },
      {
        value: 'Mobility & Disability Aids',
        label: 'Mobility & Disability Aids',
        keywords: [
          'Wheelchair',
          'Walker',
          'Scooter',
          'Crutches',
          'Cane',
          'Ramp',
          'Hoist',
        ],
      },
      {
        value: 'Diagnostic Devices',
        label: 'Diagnostic Devices',
        keywords: [
          'Monitor',
          'Thermometer',
          'Stethoscope',
          'Scale',
          'Syringe',
          'Cuff',
          'Device',
        ],
      },
    ],
  },
  {
    value: 'Automotive Tools & Maintenance',
    label: 'Automotive Tools & Maintenance',
    children: [
      {
        value: 'Garage Tools',
        label: 'Garage Tools',
        keywords: [
          'Toolbox',
          'Wrench',
          'Socket',
          'Jack',
          'Compressor',
          'Pliers',
          'Screwdriver',
          'Drill',
          'Lift',
          'Hoist',
        ],
      },
      {
        value: 'Vehicle Care & Cleaning',
        label: 'Vehicle Care & Cleaning',
        keywords: [
          'Wax',
          'Polisher',
          'Cleaner',
          'Vacuum',
          'Sponge',
          'Bucket',
          'Polish',
          'Towel',
        ],
      },
      {
        value: 'Tires & Rims',
        label: 'Tires & Rims',
        keywords: ['Tire', 'Wheel', 'Rim', 'Hub', 'Hubcap', 'Alloy', 'Tread'],
      },
      {
        value: 'Oil & Fluids',
        label: 'Oil & Fluids',
        keywords: [
          'Oil',
          'Fluid',
          'Coolant',
          'Lubricant',
          'Antifreeze',
          'Grease',
          'Bottle',
          'Jug',
        ],
      },
    ],
  },
  {
    value: 'Industrial & Business Equipment',
    label: 'Industrial & Business Equipment',
    children: [
      {
        value: 'commercial-machinery',
        label: 'Heavy Machinery & Industrial',
        keywords: [
          'Forklift',
          'Crane',
          'Excavator',
          'Tractor',
          'Generator',
          'Compressor',
          'Bulldozer',
          'Loader',
          'Backhoe',
          'Machine',
        ],
      },
      {
        value: 'business-office',
        label: 'Office & Commercial Furniture',
        keywords: [
          'Cabinet',
          'Desk',
          'Table',
          'Printer',
          'Copier',
          'Cubicle',
          'Whiteboard',
          'Chair',
        ],
      },
      {
        value: 'restaurant-equipment',
        label: 'Restaurant & Food Service',
        keywords: [
          'Refrigerator',
          'Fryer',
          'Oven',
          'Machine',
          'Mixer',
          'Slicer',
          'Grill',
          'Dispenser',
          'Vending',
          'Cooler',
        ],
      },
      {
        value: 'containers-bulk',
        label: 'Containers & Bulk Storage',
        keywords: [
          'Container',
          'Pallet',
          'Crate',
          'Barrel',
          'Drum',
          'Tank',
          'Bin',
          'Silo',
          'Carton',
          'Box',
        ],
      },
      {
        value: 'farming-equipment',
        label: 'Farming & Agriculture',
        keywords: [
          'Harvester',
          'Tractor',
          'Plow',
          'Baler',
          'Seeder',
          'Mower',
          'Machine',
        ],
      },
      {
        value: 'scrap-metal-bulk',
        label: 'Scrap & Salvage Material',
        keywords: [
          'Scrap',
          'Metal',
          'Wood',
          'Junk',
          'Debris',
          'Rubble',
          'Pile',
          'Pipe',
          'Wire',
        ],
      },
    ],
  },
  {
    value: 'Media, Music & Software',
    label: 'Media, Music & Software',
    children: [
      {
        value: 'video-movies',
        label: 'Movies & TV Shows (Physical)',
        keywords: [
          'DVD',
          'Blu-ray',
          'Disc',
          'Tape',
          'Cassette',
          'VHS',
          'Case',
          'Box',
        ],
      },
      {
        value: 'music-albums',
        label: 'Music (CDs, Vinyl, Tapes)',
        keywords: [
          'CD',
          'Vinyl',
          'Cassette',
          'Record',
          'Tape',
          'LP',
          'Album',
          'Disc',
        ],
      },
      {
        value: 'video-games-physical',
        label: 'Video Games (Physical)',
        keywords: ['Game', 'Disc', 'Cartridge', 'Console', 'Case', 'Box'],
      },
      {
        value: 'computer-software-box',
        label: 'Boxed Computer Software',
        keywords: ['Software', 'Box', 'CD', 'DVD', 'Floppy', 'Disc', 'Case'],
      },
    ],
  },
  {
    value: 'Hobbies & Recreation',
    label: 'Hobbies & Recreation',
    children: [
      {
        value: 'model-trains-rc',
        label: 'Models, RC & Drones',
        keywords: [
          'Model',
          'Train',
          'Car',
          'Plane',
          'Drone',
          'Quadcopter',
          'Helicopter',
          'Remote',
          'Controller',
        ],
      },
      {
        value: 'science-nature-hobby',
        label: 'Science & Nature Hobbies',
        keywords: [
          'Telescope',
          'Microscope',
          'Binoculars',
          'Magnifier',
          'Lens',
          'Tripod',
        ],
      },
      {
        value: 'fishing-hunting',
        label: 'Fishing & Hunting Gear',
        keywords: [
          'Rod',
          'Reel',
          'Bow',
          'Arrow',
          'Tackle',
          'Bait',
          'Lure',
          'Net',
          'Rifle',
          'Camo',
        ],
      },
      {
        value: 'maternity-infant-care',
        label: 'Maternity & Infant Essentials',
        keywords: [
          'Pump',
          'Formula',
          'Diaper',
          'Bib',
          'Bottle',
          'Pacifier',
          'Wipes',
          'Pad',
        ],
      },
      {
        value: 'travel-luggage',
        label: 'Travel & Luggage',
        keywords: [
          'Suitcase',
          'Backpack',
          'Bag',
          'Trunk',
          'Briefcase',
          'Duffel',
          'Luggage',
          'Tote',
        ],
      },
      {
        value: 'camping-outdoor',
        label: 'Camping & Outdoor Gear',
        keywords: [
          'Tent',
          'Bag',
          'Stove',
          'Lantern',
          'Cooler',
          'Backpack',
          'Mat',
          'Compass',
          'Axe',
        ],
      },
    ],
  },
  {
    value: 'Real Estate & Property',
    label: 'Real Estate & Property',
    children: [
      {
        value: 'Apartments & Homes for Sale',
        label: 'Apartments & Homes for Sale',
        keywords: [
          'House',
          'Home',
          'Villa',
          'Condo',
          'Mansion',
          'Cottage',
          'Cabin',
          'Townhouse',
          'Building',
          'Porch',
        ],
      },
      {
        value: 'Apartments & Homes for Rent',
        label: 'Apartments & Homes for Rent',
        keywords: [
          'Apartment',
          'House',
          'Building',
          'Balcony',
          'Room',
          'Flat',
          'Studio',
        ],
      },
      {
        value: 'Commercial & Office Space',
        label: 'Commercial & Office Space',
        keywords: [
          'Office',
          'Warehouse',
          'Retail',
          'Storefront',
          'Factory',
          'Skyscraper',
          'Building',
        ],
      },
      {
        value: 'Land & Plots',
        label: 'Land & Plots',
        keywords: [
          'Land',
          'Plot',
          'Field',
          'Yard',
          'Pasture',
          'Meadow',
          'Lot',
          'Soil',
          'Ground',
        ],
      },
    ],
  },
  {
    value: 'Others',
    label: 'Others',
    children: [
      {
        value: 'Pet Supplies',
        label: 'Pet Supplies',
        keywords: [
          'Food',
          'Collar',
          'Litter',
          'Aquarium',
          'Cage',
          'Bed',
          'Leash',
          'Harness',
          'Bowl',
          'Toy',
          'Tank',
          'Terrarium',
        ],
      },
      {
        value: 'Sports Equipment',
        label: 'Sports Equipment',
        keywords: [
          'Ball',
          'Racket',
          'Club',
          'Bat',
          'Helmet',
          'Net',
          'Goal',
          'Skateboard',
          'Surfboard',
          'Ski',
          'Snowboard',
          'Pad',
        ],
      },
      {
        value: 'Tools-Hardware-DIY',
        label: 'Tools, Hardware & DIY',
        keywords: [
          'Tool',
          'Drill',
          'Saw',
          'Hammer',
          'Wrench',
          'Screwdriver',
          'Ladder',
          'Pliers',
          'Level',
          'Grinder',
          'Sander',
          'Nail',
          'Screw',
        ],
      },
      {
        value: 'Collectibles & Antiques',
        label: 'Collectibles & Antiques',
        keywords: [
          'Antique',
          'Collectible',
          'Artifact',
          'Coin',
          'Stamp',
          'Vase',
          'Relic',
          'Sculpture',
          'Figurine',
          'Painting',
        ],
      },
      {
        value: 'non-perishables',
        label: 'Non-Perishable Food & Drink',
        keywords: [
          'Food',
          'Drink',
          'Coffee',
          'Tea',
          'Can',
          'Bottle',
          'Jar',
          'Packet',
          'Tin',
          'Box',
        ],
      },
    ],
  },
]
