export const options = [
  {
    value: "Electronics",
    label: "Electronics",
    children: [
      {
        value: "Mobile Phones",
        label: "Mobile Phones",
        keywords: [
          "mobile phone",
          "smartphone",
          "cell phone",
          "cellphone",
          "iphone",
          "android phone",
          "feature phone",
          "flip phone",
          "touchscreen",
          "handheld device",
          "phone",
          "samsung",
          "nokia",
          "pixel",
          "huawei",
          "oneplus",
          "xiaomi",
          "smart phone",
          "device",
          "electronics",
        ],
      },
      {
        value: "Laptops & Computers",
        label: "Laptops & Computers",
        keywords: [
          "laptop",
          "notebook",
          "computer",
          "desktop",
          "pc",
          "macbook",
          "chromebook",
          "ultrabook",
          "workstation",
          "gaming laptop",
          "imac",
          "mac",
          "windows pc",
          "linux pc",
          "keyboard",
          "screen",
          "monitor",
          "portable computer",
          "personal computer",
          "device",
          "electronics",
        ],
      },
      {
        value: "Tablets",
        label: "Tablets",
        keywords: [
          "tablet",
          "ipad",
          "e-reader",
          "kindle",
          "surface",
          "android tablet",
          "nexus tablet",
          "fire tablet",
          "tablet pc",
          "touchscreen device",
          "handheld device",
          "device",
          "electronics",
        ],
      },
      {
        value: "TVs & Monitors",
        label: "TVs & Monitors",
        keywords: [
          "tv",
          "television",
          "monitor",
          "screen",
          "flat screen",
          "led tv",
          "lcd monitor",
          "oled tv",
          "plasma tv",
          "curved monitor",
          "display",
          "television screen",
          "device",
          "electronics",
        ],
      },
      {
        value: "Cameras",
        label: "Cameras",
        keywords: [
          "camera",
          "digital camera",
          "dslr",
          "mirrorless camera",
          "video camera",
          "camcorder",
          "action camera",
          "gopro",
          "canon",
          "nikon",
          "sony camera",
          "panasonic camera",
          "lens",
          "photography",
          "photo camera",
          "point and shoot",
          "device",
          "electronics",
        ],
      },
      {
        value: "Audio & Headphones",
        label: "Audio & Headphones",
        keywords: [
          "headphones",
          "earbuds",
          "earphones",
          "speaker",
          "speakers",
          "sound system",
          "bluetooth speaker",
          "headset",
          "sony headphones",
          "bose",
          "beats",
          "audio device",
          "earbud",
          "wireless headphones",
          "over ear headphones",
          "in ear headphones",
          "music device",
          "device",
          "electronics",
        ],
      },
      {
        value: "Gaming Consoles",
        label: "Gaming Consoles",
        keywords: [
          "game console",
          "gaming console",
          "controller",
          "joystick",
          "playstation",
          "xbox",
          "nintendo switch",
          "ps4",
          "ps5",
          "xbox one",
          "xbox series x",
          "handheld console",
          "gamepad",
          "switch",
          "video game system",
          "device",
          "electronics",
        ],
      },
      {
        value: "Wearables",
        label: "Wearables",
        keywords: [
          "smartwatch",
          "fitness tracker",
          "wearable",
          "wristwatch",
          "band",
          "health tracker",
          "fitbit",
          "garmin",
          "apple watch",
          "wearable device",
          "activity tracker",
          "smart band",
          "watch",
          "device",
          "electronics",
        ],
      },
      {
        value: "Accessories & Cables",
        label: "Accessories & Cables",
        keywords: [
          "charger",
          "usb cable",
          "adapter",
          "headset",
          "earphones",
          "power bank",
          "hdmi cable",
          "cable",
          "dongle",
          "usb-c cable",
          "lightning cable",
          "earbud cable",
          "charging cable",
          "power adapter",
          "wire",
          "connector",
          "device",
          "electronics",
        ],
      },
    ],
  },
  {
    value: "Home & Furniture",
    label: "Home & Furniture",
    children: [
      {
        value: "Sofas & Chairs",
        label: "Sofas & Chairs",
        keywords: [
          "sofa",
          "couch",
          "armchair",
          "chair",
          "recliner",
          "stool",
          "bench",
          "loveseat",
          "chaise",
          "ottoman",
          "rocking chair",
          "furniture",
          "home",
          "seat",
        ],
      },
      {
        value: "Tables & Desks",
        label: "Tables & Desks",
        keywords: [
          "table",
          "desk",
          "dining table",
          "coffee table",
          "side table",
          "console table",
          "writing desk",
          "study desk",
          "bedside table",
          "office desk",
          "kitchen table",
          "furniture",
          "home",
        ],
      },
      {
        value: "Beds & Mattresses",
        label: "Beds & Mattresses",
        keywords: [
          "bed",
          "mattress",
          "bunk bed",
          "canopy bed",
          "sofa bed",
          "futon",
          "crib",
          "cot",
          "queen bed",
          "king bed",
          "single bed",
          "double bed",
          "infant bed",
          "furniture",
          "home",
          "sleeping",
        ],
      },
      {
        value: "Storage",
        label: "Storage",
        keywords: [
          "cabinet",
          "closet",
          "dresser",
          "bookshelf",
          "drawer",
          "wardrobe",
          "shelf",
          "chest",
          "storage unit",
          "cupboard",
          "armoire",
          "rack",
          "furniture",
          "home",
        ],
      },
      {
        value: "Home Decor",
        label: "Home Decor",
        keywords: [
          "lamp",
          "floor lamp",
          "table lamp",
          "light",
          "lighting",
          "curtain",
          "rug",
          "cushion",
          "vase",
          "painting",
          "mirror",
          "decorative item",
          "wall art",
          "photo frame",
          "clock",
          "plant",
          "artwork",
          "decoration",
          "home ornament",
          "home",
          "furniture",
        ],
      },
      {
        value: "Kitchen Appliances",
        label: "Kitchen Appliances",
        keywords: [
          "fridge",
          "refrigerator",
          "oven",
          "microwave",
          "blender",
          "toaster",
          "coffee maker",
          "kettle",
          "stove",
          "dishwasher",
          "juicer",
          "food processor",
          "pressure cooker",
          "air fryer",
          "grill",
          "hob",
          "home",
          "appliance",
          "kitchen",
        ],
      },
      {
        value: "Lighting",
        label: "Lighting",
        keywords: [
          "lamp",
          "ceiling light",
          "chandelier",
          "light fixture",
          "bulb",
          "led light",
          "floor lamp",
          "pendant light",
          "spotlight",
          "table lamp",
          "home",
          "lighting",
        ],
      },
    ],
  },
  {
    value: "Vehicles",
    label: "Vehicles",
    children: [
      {
        value: "cars",
        label: "Cars",
        keywords: [
          "car",
          "sedan",
          "coupe",
          "convertible",
          "suv",
          "hatchback",
          "minivan",
          "pickup",
          "wagon",
          "jeep",
          "luxury car",
          "electric car",
          "automobile",
          "vehicle",
          "transport",
        ],
      },
      {
        value: "Motorbikes & Scooters",
        label: "Motorbikes & Scooters",
        keywords: [
          "motorcycle",
          "scooter",
          "moped",
          "bike",
          "motorbike",
          "harley davidson",
          "yamaha",
          "kawasaki",
          "ducati",
          "honda bike",
          "motor vehicle",
          "vehicle",
          "transport",
        ],
      },
      {
        value: "Bicycles",
        label: "Bicycles",
        keywords: [
          "bicycle",
          "bike",
          "tricycle",
          "mountain bike",
          "road bike",
          "road bicycle",
          "kids bike",
          "cycling",
          "vehicle",
          "transport",
        ],
      },
      {
        value: "Auto Parts & Accessories",
        label: "Auto Parts & Accessories",
        keywords: [
          "wheel",
          "tire",
          "engine",
          "car part",
          "mirror",
          "bumper",
          "headlight",
          "tail light",
          "gear",
          "car accessory",
          "brake",
          "clutch",
          "axle",
          "automobile part",
          "vehicle",
          "transport",
        ],
      },
    ],
  },
  {
    value: "Fashion",
    label: "Fashion",
    children: [
      {
        value: "Men’s Clothing",
        label: "Men’s Clothing",
        keywords: [
          "shirt",
          "t-shirt",
          "jeans",
          "trousers",
          "pants",
          "jacket",
          "coat",
          "sweater",
          "hoodie",
          "suit",
          "blazer",
          "shorts",
          "polo",
          "cardigan",
          "vest",
          "top",
          "formal shirt",
          "clothing",
          "apparel",
          "fashion",
        ],
      },
      {
        value: "Women’s Clothing",
        label: "Women’s Clothing",
        keywords: [
          "dress",
          "blouse",
          "skirt",
          "jeans",
          "trousers",
          "pants",
          "jacket",
          "coat",
          "sweater",
          "cardigan",
          "top",
          "tunic",
          "shorts",
          "hoodie",
          "vest",
          "evening gown",
          "blazer",
          "clothing",
          "apparel",
          "fashion",
        ],
      },
      {
        value: "Footwear",
        label: "Footwear",
        keywords: [
          "shoe",
          "boot",
          "sneaker",
          "sandals",
          "heels",
          "loafers",
          "flip flops",
          "running shoes",
          "trainers",
          "slippers",
          "oxford shoes",
          "canvas shoes",
          "athletic shoes",
          "clothing",
          "apparel",
          "fashion",
        ],
      },
      {
        value: "Bags & Luggage",
        label: "Bags & Luggage",
        keywords: [
          "bag",
          "backpack",
          "purse",
          "handbag",
          "suitcase",
          "duffle bag",
          "tote",
          "luggage",
          "wallet",
          "carry-on",
          "briefcase",
          "satchel",
          "clothing",
          "apparel",
          "fashion",
        ],
      },
      {
        value: "Jewelry & Watches",
        label: "Jewelry & Watches",
        keywords: [
          "wristwatch",
          "watch",
          "ring",
          "necklace",
          "bracelet",
          "earring",
          "bangle",
          "cufflink",
          "pendant",
          "charm bracelet",
          "jewelry",
          "accessory",
          "clothing",
          "apparel",
          "fashion",
        ],
      },
    ],
  },
  {
    value: "Books & Education",
    label: "Books & Education",
    children: [
      {
        value: "Textbooks",
        label: "Textbooks",
        keywords: [
          "textbook",
          "book",
          "study material",
          "learning",
          "education",
          "reading",
          "literature",
          "books",
          "education",
        ],
      },
      {
        value: "Exam Materials",
        label: "Exam Materials",
        keywords: [
          "exam",
          "exam paper",
          "test material",
          "question paper",
          "study",
          "books",
          "education",
          "learning",
        ],
      },
      {
        value: "Novels",
        label: "Novels",
        keywords: [
          "novel",
          "book",
          "literature",
          "fiction",
          "reading",
          "books",
          "education",
          "learning",
        ],
      },
      {
        value: "Study Tables/Chairs",
        label: "Study Tables/Chairs",
        keywords: ["desk", "chair", "study table", "furniture", "home", "seat"],
      },
      {
        value: "Stationery",
        label: "Stationery",
        keywords: [
          "pen",
          "pencil",
          "notebook",
          "paper",
          "stationery",
          "writing",
          "school",
          "office",
          "books",
          "education",
        ],
      },
    ],
  },
  {
    value: "Kids & Toys",
    label: "Kids & Toys",
    children: [
      {
        value: "toys-games",
        label: "Toys & Games",
        keywords: [
          "toy",
          "game",
          "lego",
          "board game",
          "action figure",
          "puzzle",
          "play",
          "kids",
          "child",
          "kids toy",
          "toy item",
          "entertainment",
          "fun",
        ],
      },
      {
        value: "Baby Gear",
        label: "Baby Gear",
        keywords: [
          "stroller",
          "crib",
          "baby seat",
          "high chair",
          "baby carrier",
          "diaper bag",
          "infant",
          "kids",
          "child",
          "baby",
        ],
      },
      {
        value: "Kids’ Clothing",
        label: "Kids’ Clothing",
        keywords: [
          "shirt",
          "t-shirt",
          "pants",
          "trousers",
          "dress",
          "skirt",
          "jacket",
          "coat",
          "clothing",
          "apparel",
          "kids",
          "child",
        ],
      },
      {
        value: "Strollers & Cribs",
        label: "Strollers & Cribs",
        keywords: [
          "stroller",
          "crib",
          "baby bed",
          "pushchair",
          "baby furniture",
          "infant",
          "kids",
          "child",
        ],
      },
    ],
  },
  {
    value: "Others",
    label: "Others",
    children: [
      {
        value: "Pet Supplies",
        label: "Pet Supplies",
        keywords: [
          "pet",
          "dog",
          "cat",
          "bird",
          "fish",
          "aquarium",
          "toy",
          "food",
          "animal",
          "pet supplies",
        ],
      },
      {
        value: "Sports Equipment",
        label: "Sports Equipment",
        keywords: [
          "ball",
          "bat",
          "racket",
          "sports",
          "equipment",
          "exercise",
          "fitness",
          "gym",
          "athletic",
        ],
      },
      {
        value: "Musical Instruments",
        label: "Musical Instruments",
        keywords: [
          "guitar",
          "piano",
          "violin",
          "drums",
          "flute",
          "instrument",
          "music",
          "musical",
        ],
      },
      {
        value: "Tools & Machinery",
        label: "Tools & Machinery",
        keywords: [
          "tool",
          "drill",
          "saw",
          "hammer",
          "machine",
          "equipment",
          "hardware",
          "construction",
          "work",
          "repair",
        ],
      },
      {
        value: "Collectibles & Antiques",
        label: "Collectibles & Antiques",
        keywords: [
          "antique",
          "collectible",
          "vintage",
          "artifact",
          "old",
          "rare",
          "memorabilia",
        ],
      },
    ],
  },
];
