export const options = [
  {
    value: 'Electronics',
    label: 'Electronics',
    children: [
      {
        value: 'Mobile Phones',
        label: 'Mobile Phones',
        keywords: [
          'mobile phone',
          'smartphone',
          'cell phone',
          'cellphone',
          'handheld device',
          'communication device',
          'iphone',
          'android phone',
          'feature phone',
          'flip phone',
          'touchscreen phone',
          'slider phone',
          'samsung galaxy',
          'nokia',
          'google pixel',
          'huawei',
          'oneplus',
          'xiaomi',
          'motorola',
          'oppo',
          'smart phone',
          'phone',
          'unlocked phone',
          'gsm',
          'cdma',
          'sim card',
          'camera phone',
          'pda',
          'telephony',
          'telecommunication',
          'mini computer',
        ],
      },
      {
        value: 'Laptops & Computers',
        label: 'Laptops & Computers',
        keywords: [
          'laptop',
          'notebook',
          'computer',
          'desktop',
          'pc',
          'macbook',
          'chromebook',
          'ultrabook',
          'workstation',
          'gaming tower',
          'imac',
          'mac mini',
          'windows pc',
          'linux pc',
          'all-in-one pc',
          'tower computer',
          'cpu',
          'processor',
          'gpu',
          'ram',
          'hard drive',
          'solid state drive',
          'motherboard',
          'computer hardware',
          'portable computer',
          'personal computer',
          'server',
          'mainframe',
        ],
      },
      {
        value: 'Peripherals & Input Devices',
        label: 'Peripherals & Input Devices',
        keywords: [
          'monitor',
          'screen',
          'keyboard',
          'mouse',
          'webcam',
          'printer',
          'scanner',
          'external hard drive',
          'usb drive',
          'joystick',
          'trackball',
          'gaming mouse',
          'mechanical keyboard',
          'display',
          'input device',
          'output device',
          'usb hub',
          'kensington',
          'logitech',
          'razer',
          'corsair',
        ],
      },
      {
        value: 'Tablets',
        label: 'Tablets',
        keywords: [
          'tablet',
          'ipad',
          'e-reader',
          'kindle',
          'surface tablet',
          'android tablet',
          'nexus tablet',
          'fire tablet',
          'tablet pc',
          'touchscreen device',
          'slate computer',
          'digital notebook',
          'stylus',
          'pen input',
          'portable screen',
          'reading device',
          'graphic tablet',
          'handheld computer',
        ],
      },
      {
        value: 'TVs & Monitors',
        label: 'TVs & Monitors',
        keywords: [
          'tv',
          'television',
          'monitor',
          'screen',
          'display',
          'flat screen',
          'led tv',
          'lcd monitor',
          'oled tv',
          'plasma tv',
          'curved monitor',
          'smart tv',
          '4k tv',
          '8k tv',
          'hdtv',
          'projector',
          'display panel',
          'television screen',
          'broadcast receiver',
        ],
      },
      {
        value: 'Cameras',
        label: 'Cameras',
        keywords: [
          'camera',
          'digital camera',
          'dslr',
          'mirrorless camera',
          'video camera',
          'camcorder',
          'action camera',
          'gopro',
          'canon eos',
          'nikon z series',
          'sony alpha',
          'panasonic lumix',
          'lens',
          'photography',
          'photo camera',
          'point and shoot',
          'instant camera',
          'security camera',
          'webcam',
          'film camera',
          'tripod',
          'flash',
          'aperture',
          'shutter',
        ],
      },
      {
        value: 'Audio & Headphones',
        label: 'Audio & Headphones',
        keywords: [
          'headphones',
          'earbuds',
          'earphones',
          'speaker',
          'speakers',
          'sound system',
          'bluetooth speaker',
          'headset',
          'sony headphones',
          'bose',
          'beats',
          'jbl',
          'sennheiser',
          'audio device',
          'stereo',
          'wireless headphones',
          'over ear headphones',
          'in ear headphones',
          'music device',
          'amplifier',
          'subwoofer',
          'soundbar',
          'microphone',
          'turntable',
          'vinyl player',
          'boombox',
          'hifi',
        ],
      },
      {
        value: 'Gaming Consoles',
        label: 'Gaming Consoles',
        keywords: [
          'game console',
          'gaming console',
          'controller',
          'joystick',
          'playstation',
          'xbox',
          'nintendo switch',
          'ps4',
          'ps5',
          'xbox one',
          'xbox series x',
          'handheld console',
          'gamepad',
          'switch',
          'wii',
          'atari',
          'sega',
          'video game system',
          'arcade machine',
          'vr headset',
        ],
      },
      {
        value: 'Wearables',
        label: 'Wearables',
        keywords: [
          'smartwatch',
          'fitness tracker',
          'wearable device',
          'wristwatch',
          'band',
          'health tracker',
          'fitbit',
          'garmin',
          'apple watch',
          'samsung gear',
          'activity tracker',
          'smart ring',
          'smart band',
          'digital watch',
          'pedometer',
          'heart rate monitor',
          'sleep tracker',
        ],
      },
      {
        value: 'Accessories & Cables',
        label: 'Accessories & Cables',
        keywords: [
          'charger',
          'usb cable',
          'adapter',
          'power adapter',
          'power bank',
          'hdmi cable',
          'vga cable',
          'ethernet cable',
          'dongle',
          'usb-c cable',
          'lightning cable',
          'charging cable',
          'wire',
          'connector',
          'battery pack',
          'phone case',
          'screen protector',
          'stylus pen',
          'hub',
          'cable organizer',
          'surge protector',
        ],
      },
    ],
  },
  {
    value: 'Home & Furniture',
    label: 'Home & Furniture',
    children: [
      {
        value: 'Sofas & Chairs',
        label: 'Sofas & Chairs',
        keywords: [
          'sofa',
          'couch',
          'armchair',
          'chair',
          'recliner',
          'stool',
          'bench',
          'loveseat',
          'chaise lounge',
          'ottoman',
          'rocking chair',
          'sectional sofa',
          'fainting couch',
          'dining chair',
          'office chair',
          'bean bag chair',
          'seating',
          'upholstery',
          'leather sofa',
          'fabric chair',
          'furniture seat',
        ],
      },
      {
        value: 'Tables & Desks',
        label: 'Tables & Desks',
        keywords: [
          'table',
          'desk',
          'dining table',
          'coffee table',
          'side table',
          'end table',
          'console table',
          'writing desk',
          'study desk',
          'bedside table',
          'nightstand',
          'office desk',
          'kitchen table',
          'console table',
          'bar table',
          'trestle desk',
          'wooden table',
          'glass table',
          'surface area',
        ],
      },
      {
        value: 'Beds & Mattresses',
        label: 'Beds & Mattresses',
        keywords: [
          'bed',
          'mattress',
          'bunk bed',
          'canopy bed',
          'sofa bed',
          'futon',
          'crib',
          'cot',
          'bassinet',
          'queen bed',
          'king bed',
          'single bed',
          'double bed',
          'trundle bed',
          'headboard',
          'footboard',
          'box spring',
          'bed frame',
          'infant bed',
          'sleeping surface',
          'inflatable mattress',
          'memory foam',
        ],
      },
      {
        value: 'Storage',
        label: 'Storage',
        keywords: [
          'cabinet',
          'closet',
          'dresser',
          'bookshelf',
          'drawer',
          'wardrobe',
          'shelf',
          'chest of drawers',
          'storage unit',
          'cupboard',
          'armoire',
          'rack',
          'filing cabinet',
          'sideboard',
          'buffet',
          'media console',
          'display case',
          'locker',
          'shelving',
        ],
      },
      {
        value: 'Home Decor',
        label: 'Home Decor',
        keywords: [
          'lamp',
          'floor lamp',
          'table lamp',
          'curtain',
          'drapery',
          'rug',
          'area rug',
          'cushion',
          'throw pillow',
          'vase',
          'ceramic vase',
          'painting',
          'wall art',
          'mirror',
          'photo frame',
          'picture frame',
          'clock',
          'wall clock',
          'decorative item',
          'sculpture',
          'plant',
          'artwork',
          'decoration',
          'home ornament',
          'tapestry',
          'candle holder',
          'trinket',
        ],
      },
      {
        value: 'Kitchen Appliances',
        label: 'Kitchen Appliances',
        keywords: [
          'fridge',
          'refrigerator',
          'oven',
          'microwave',
          'blender',
          'toaster',
          'coffee maker',
          'kettle',
          'stove',
          'range',
          'dishwasher',
          'juicer',
          'food processor',
          'pressure cooker',
          'air fryer',
          'grill',
          'hob',
          'mixer',
          'stand mixer',
          'slow cooker',
          'crock pot',
          'cooking appliance',
          'kitchen gadget',
          'extractor hood',
        ],
      },
      {
        value: 'Lighting',
        label: 'Lighting',
        keywords: [
          'lamp',
          'ceiling light',
          'chandelier',
          'light fixture',
          'bulb',
          'led light',
          'fluorescent light',
          'pendant light',
          'spotlight',
          'table lamp',
          'wall sconce',
          'lantern',
          'illumination',
          'lighting element',
          'light source',
          'filament bulb',
          'lighting',
        ],
      },
    ],
  },
  {
    value: 'Vehicles',
    label: 'Vehicles',
    children: [
      {
        value: 'cars',
        label: 'Cars',
        keywords: [
          'car',
          'sedan',
          'coupe',
          'convertible',
          'suv',
          'hatchback',
          'minivan',
          'pickup truck',
          'wagon',
          'jeep',
          'luxury car',
          'electric car',
          'hybrid vehicle',
          'truck',
          'van',
          'limousine',
          'automobile',
          'vehicle',
          'transport',
          'motor vehicle',
          'race car',
          'sports car',
        ],
      },
      {
        value: 'Caravans & Motorhomes',
        label: 'Caravans & Motorhomes',
        keywords: [
          'caravan',
          'motorhome',
          'campervan',
          'rv',
          'trailer',
          'static caravan',
          'towed vehicle',
          'mobile home',
        ],
      },
      {
        value: 'Motorbikes & Scooters',
        label: 'Motorbikes & Scooters',
        keywords: [
          'motorcycle',
          'scooter',
          'moped',
          'bike',
          'motorbike',
          'harley davidson',
          'yamaha',
          'kawasaki',
          'ducati',
          'honda bike',
          'motor vehicle',
          'transport',
          'dirt bike',
          'cruiser',
          'sport bike',
          'atv',
          'quad bike',
          'two-wheeler',
        ],
      },
      {
        value: 'Bicycles',
        label: 'Bicycles',
        keywords: [
          'bicycle',
          'bike',
          'tricycle',
          'mountain bike',
          'road bike',
          'road bicycle',
          'kids bike',
          'biking',
          'cycling',
          'commuter bike',
          'bmx',
          'folding bike',
          'electric bike',
          'pedal cycle',
          'unicycle',
          'non-motorized vehicle',
        ],
      },
      {
        value: 'Auto Parts & Accessories',
        label: 'Auto Parts & Accessories',
        keywords: [
          'wheel',
          'tire',
          'rim',
          'engine',
          'car part',
          'mirror',
          'side mirror',
          'bumper',
          'headlight',
          'tail light',
          'gearbox',
          'car accessory',
          'brake system',
          'clutch',
          'axle',
          'automobile part',
          'spark plug',
          'battery',
          'radiator',
          'steering wheel',
          'windshield',
          'dashboard',
          'seat belt',
        ],
      },
    ],
  },
  {
    value: 'Fashion',
    label: 'Fashion',
    children: [
      {
        value: 'Men’s Clothing',
        label: 'Men’s Clothing',
        keywords: [
          'shirt',
          't-shirt',
          'jeans',
          'denim',
          'trousers',
          'pants',
          'jacket',
          'coat',
          'sweater',
          'hoodie',
          'suit',
          'blazer',
          'shorts',
          'polo shirt',
          'cardigan',
          'vest',
          'top',
          'formal shirt',
          'tie',
          'bow tie',
          'socks',
          'underwear',
          'pajamas',
          "men's apparel",
          'male fashion',
          'clothing',
        ],
      },
      {
        value: 'Women’s Clothing',
        label: 'Women’s Clothing',
        keywords: [
          'dress',
          'blouse',
          'skirt',
          'jeans',
          'denim',
          'trousers',
          'pants',
          'jacket',
          'coat',
          'sweater',
          'cardigan',
          'top',
          'tunic',
          'shorts',
          'hoodie',
          'vest',
          'evening gown',
          'blazer',
          'lingerie',
          'bra',
          'panties',
          'stockings',
          'leggings',
          "women's apparel",
          'female fashion',
          'clothing',
        ],
      },
      {
        value: 'Footwear',
        label: 'Footwear',
        keywords: [
          'shoe',
          'boot',
          'sneaker',
          'sandals',
          'heels',
          'loafers',
          'flip flops',
          'running shoes',
          'trainers',
          'slippers',
          'oxford shoes',
          'canvas shoes',
          'athletic shoes',
          'foot apparel',
          'dress shoes',
          'work boots',
          'wellington boots',
          'footwear',
          'moccasins',
        ],
      },
      {
        value: 'Bags & Luggage',
        label: 'Bags & Luggage',
        keywords: [
          'bag',
          'backpack',
          'purse',
          'handbag',
          'suitcase',
          'duffle bag',
          'tote bag',
          'luggage',
          'wallet',
          'carry-on',
          'briefcase',
          'satchel',
          'clutch bag',
          'messenger bag',
          'fanny pack',
          'travel bag',
          'saddlebag',
          'valise',
          'accessory',
        ],
      },
      {
        value: 'Jewelry & Watches',
        label: 'Jewelry & Watches',
        keywords: [
          'wristwatch',
          'watch',
          'ring',
          'necklace',
          'bracelet',
          'earring',
          'bangle',
          'cufflink',
          'pendant',
          'charm bracelet',
          'tiara',
          'brooch',
          'jewelry',
          'accessory',
          'diamond',
          'gold',
          'silver',
          'precious metal',
          'gemstone',
          'timepiece',
          'fashion accessory',
        ],
      },
    ],
  },
  {
    value: 'Books & Education',
    label: 'Books & Education',
    children: [
      {
        value: 'Textbooks',
        label: 'Textbooks',
        keywords: [
          'textbook',
          'book',
          'course book',
          'study material',
          'learning resource',
          'academic text',
          'scholarly book',
          'college textbook',
          'school book',
          'manual',
          'education',
          'reading',
        ],
      },
      {
        value: 'Novels',
        label: 'Novels',
        keywords: [
          'novel',
          'book',
          'literature',
          'fiction',
          'paperback',
          'hardcover',
          'story book',
          'fantasy novel',
          'thriller',
          'romance novel',
          'graphic novel',
          'reading material',
          'prose',
        ],
      },
      {
        value: 'Study Tables/Chairs',
        label: 'Study Tables/Chairs',
        keywords: [
          'desk',
          'chair',
          'study table',
          'writing table',
          'office furniture',
          'student desk',
          'ergonomic chair',
          'task chair',
          'home office desk',
          'table',
          'seat',
        ],
      },
      {
        value: 'Stationery',
        label: 'Stationery',
        keywords: [
          'pen',
          'pencil',
          'notebook',
          'paper',
          'stationery',
          'writing tool',
          'school supplies',
          'office supplies',
          'stapler',
          'tape',
          'folder',
          'binder',
          'eraser',
          'ruler',
          'clipboard',
          'marker',
          'adhesive notes',
        ],
      },
    ],
  },
  {
    value: 'Kids & Toys',
    label: 'Kids & Toys',
    children: [
      {
        value: 'toys-games',
        label: 'Toys & Games',
        keywords: [
          'toy',
          'game',
          'lego',
          'board game',
          'action figure',
          'puzzle',
          'doll',
          'stuffed animal',
          'plush toy',
          'building blocks',
          'remote control car',
          'kids toy',
          'play item',
          'entertainment',
          'toy train',
          'video game',
          'baby toy',
        ],
      },
      {
        value: 'Baby Gear',
        label: 'Baby Gear',
        keywords: [
          'baby seat',
          'high chair',
          'baby carrier',
          'diaper bag',
          'booster seat',
          'infant seat',
          'baby monitor',
          'bottle warmer',
          'nursing pillow',
          'child care equipment',
        ],
      },
      {
        value: 'Kids’ Clothing',
        label: 'Kids’ Clothing',
        keywords: [
          'shirt',
          't-shirt',
          'pants',
          'trousers',
          'dress',
          'skirt',
          'jacket',
          'coat',
          'onesie',
          "children's clothing",
          'kids apparel',
          'toddler outfit',
          'baby clothes',
          'footie pajamas',
        ],
      },
      {
        value: 'Strollers & Cribs',
        label: 'Strollers & Cribs',
        keywords: [
          'stroller',
          'crib',
          'baby bed',
          'pushchair',
          'pram',
          'baby carriage',
          'travel system',
          'pack n play',
          'playard',
          'infant furniture',
          'toddler bed',
        ],
      },
    ],
  },
  {
    value: 'Art, Crafts & Supplies',
    label: 'Art, Crafts & Supplies',
    children: [
      {
        value: 'Art Supplies',
        label: 'Art Supplies',
        keywords: [
          'paint',
          'canvas',
          'brush',
          'easel',
          'acrylic paint',
          'oil paint',
          'watercolor',
          'sketchpad',
          'drawing paper',
          'charcoal',
          'pastel',
          'palette',
          'modelling clay',
          'art kit',
          'drawing supplies',
          'illustration',
          'fine art',
          'art material',
        ],
      },
      {
        value: 'Crafting & Sewing',
        label: 'Crafting & Sewing',
        keywords: [
          'sewing machine',
          'fabric',
          'yarn',
          'knitting needles',
          'crochet hook',
          'felt',
          'embroidery floss',
          'patterns',
          'craft kit',
          'scrapbooking',
          'beads',
          'jewelry making supplies',
          'quilting',
          'haberdashery',
          'diy material',
          'handmade supplies',
        ],
      },
      {
        value: 'Musical Instruments',
        label: 'Musical Instruments',
        keywords: [
          'guitar',
          'piano',
          'violin',
          'drums',
          'flute',
          'trumpet',
          'keyboard',
          'saxophone',
          'instrument',
          'music making',
          'string instrument',
          'percussion',
          'wind instrument',
          'amplifier',
          'pedals',
          'sheet music',
          'ukulele',
          'cello',
          'synthesizer',
        ],
      },
      {
        value: 'Photography Equipment',
        label: 'Photography Equipment',
        keywords: [
          'tripod',
          'camera lens',
          'flash unit',
          'lighting kit',
          'backdrop',
          'photo paper',
          'darkroom supplies',
          'filter',
          'gimbal',
          'drone camera',
          'dslr accessory',
          'mirrorless accessory',
          'studio lighting',
        ],
      },
    ],
  },
  {
    value: 'Wedding & Bridal',
    label: 'Wedding & Bridal',
    children: [
      {
        value: 'wedding-dresses',
        label: 'Wedding Dresses & Wear',
        keywords: [
          'wedding dress',
          'bridal gown',
          'bridesmaid dress',
          'mother of the bride outfit',
          'tuxedo',
          'suit hire',
          'veil',
          'tiara',
          'sash',
          'wedding shoes',
          'bridal accessories',
        ],
      },
      {
        value: 'wedding-decor',
        label: 'Wedding Decor & Supplies',
        keywords: [
          'venue decoration',
          'table centerpiece',
          'chair cover',
          'wedding signs',
          'favors',
          'table linen',
          'cake stand',
          'wedding props',
          'bunting',
          'lights (wedding)',
        ],
      },
      {
        value: 'wedding-rings',
        label: 'Engagement & Wedding Rings',
        keywords: [
          'engagement ring',
          'wedding band',
          'diamond ring',
          'jewelry (wedding)',
          'pre-owned ring',
          'proposal ring',
          'eternity ring',
          'gold band',
          'platinum ring',
        ],
      },
    ],
  },
  {
    value: 'Home Improvement & Building Supplies',
    label: 'Home Improvement & Building Supplies',
    children: [
      {
        value: 'building-materials',
        label: 'Building Materials & Supplies',
        keywords: [
          'lumber',
          'drywall',
          'plasterboard',
          'cement',
          'insulation',
          'roofing tiles',
          'shingles',
          'bricks',
          'pavers',
          'siding',
          'raw material',
          'construction material',
        ],
      },
      {
        value: 'doors-windows-fittings',
        label: 'Doors, Windows & Fittings',
        keywords: [
          'door',
          'window',
          'sash',
          'frame',
          'hardware',
          'doorknob',
          'hinge',
          'locks',
          'garage door',
          'screen door',
          'shutters',
          'pre-hung door',
        ],
      },
      {
        value: 'plumbing-fixtures',
        label: 'Plumbing & Bathroom Fixtures',
        keywords: [
          'sink',
          'toilet',
          'vanity',
          'faucet',
          'tap',
          'shower head',
          'bathtub',
          'jacuzzi',
          'piping',
          'water heater',
          'plumbing components',
        ],
      },
      {
        value: 'flooring-tiles',
        label: 'Flooring & Wall Tiles',
        keywords: [
          'hardwood flooring',
          'laminate flooring',
          'vinyl planks',
          'carpet tiles',
          'ceramic tile',
          'porcelain tile',
          'grout',
          'adhesive',
          'tiling supplies',
        ],
      },
    ],
  },
  {
    value: 'Patio, Garden & Outdoor',
    label: 'Patio, Garden & Outdoor',
    children: [
      {
        value: 'garden-tools',
        label: 'Gardening & Tools',
        keywords: [
          'lawn mower',
          'trimmer',
          'weed eater',
          'shovel',
          'rake',
          'tiller',
          'gardening tool',
          'power tool',
          'wheelbarrow',
          'irrigation',
          'sprinkler',
          'chainsaw',
          'hedge trimmer',
        ],
      },
      {
        value: 'patio-furniture',
        label: 'Patio & Outdoor Furniture',
        keywords: [
          'patio set',
          'outdoor table',
          'deck chair',
          'sun lounger',
          'umbrella',
          'awning',
          'gazebo',
          'garden bench',
          'porch swing',
          'outdoor seating',
          'rattan furniture',
        ],
      },
      {
        value: 'bbq-grill',
        label: 'BBQs & Grills',
        keywords: [
          'barbecue',
          'grill',
          'smoker',
          'charcoal grill',
          'gas grill',
          'bbq set',
          'outdoor cooking',
          'fire pit',
          'patio heater',
        ],
      },
      {
        value: 'plants-seeds',
        label: 'Plants, Seeds & Pots',
        keywords: [
          'plant',
          'flower',
          'seedling',
          'tree',
          'shrub',
          'potted plant',
          'ceramic pot',
          'planter',
          'garden pot',
          'soil',
          'fertilizer',
          'houseplant',
          'seeds',
        ],
      },
    ],
  },
  {
    value: 'Health & Medical Equipment',
    label: 'Health & Medical Equipment',
    children: [
      {
        value: 'Fitness & Exercise',
        label: 'Fitness & Exercise',
        keywords: [
          'treadmill',
          'elliptical',
          'stationary bike',
          'weights',
          'dumbbell',
          'kettlebell',
          'yoga mat',
          'resistance band',
          'gym equipment',
          'home fitness',
          'weight bench',
          'cardio machine',
        ],
      },
      {
        value: 'Personal Care & Beauty',
        label: 'Personal Care & Beauty',
        keywords: [
          'hair dryer',
          'straightener',
          'curling iron',
          'shaver',
          'electric toothbrush',
          'massager',
          'facial steamer',
          'make up kit',
          'cosmetics',
          'skincare devices',
          'beauty tools',
        ],
      },
      {
        value: 'Mobility & Disability Aids',
        label: 'Mobility & Disability Aids',
        keywords: [
          'wheelchair',
          'walker',
          'mobility scooter',
          'crutches',
          'rollator',
          'commode chair',
          'lift chair',
          'hearing aid',
          'incontinence supplies',
          'disability equipment',
          'medical aid',
        ],
      },
      {
        value: 'Diagnostic Devices',
        label: 'Diagnostic Devices',
        keywords: [
          'blood pressure monitor',
          'glucometer',
          'thermometer',
          'oximeter',
          'stethescope',
          'first aid kit',
          'medical testing kit',
          'health monitor',
          'blood sugar monitor',
        ],
      },
    ],
  },
  {
    value: 'Automotive Tools & Maintenance',
    label: 'Automotive Tools & Maintenance',
    children: [
      {
        value: 'Garage Tools',
        label: 'Garage Tools',
        keywords: [
          'tool box',
          'wrench set',
          'socket set',
          'jack stand',
          'car jack',
          'creeper',
          'air compressor',
          'diagnostic tool',
          'obd scanner',
          'engine hoist',
          'shop equipment',
          'mechanic tools',
          'automotive repair',
        ],
      },
      {
        value: 'Vehicle Care & Cleaning',
        label: 'Vehicle Care & Cleaning',
        keywords: [
          'car wash kit',
          'polisher',
          'buffer',
          'car wax',
          'car cleaner',
          'detailing supplies',
          'vacuum cleaner',
          'tire shine',
          'microfiber towel',
          'paint protection',
          'interior cleaner',
        ],
      },
      {
        value: 'Tires & Rims',
        label: 'Tires & Rims',
        keywords: [
          'tire',
          'car tire',
          'truck tire',
          'rim',
          'wheel',
          'alloy wheel',
          'steel wheel',
          'snow tire',
          'all-season tire',
          'spare tire',
          'tire pressure monitor',
          'hub cap',
        ],
      },
      {
        value: 'Oil & Fluids',
        label: 'Oil & Fluids',
        keywords: [
          'motor oil',
          'engine oil',
          'transmission fluid',
          'brake fluid',
          'coolant',
          'antifreeze',
          'lubricant',
          'power steering fluid',
          'washer fluid',
          'car fluids',
          'maintenance supplies',
        ],
      },
    ],
  },
  {
    value: 'Industrial & Business Equipment',
    label: 'Industrial & Business Equipment',
    children: [
      {
        value: 'commercial-machinery',
        label: 'Heavy Machinery & Industrial',
        keywords: [
          'forklift',
          'crane',
          'excavator',
          'tractor',
          'construction equipment',
          'industrial machine',
          'generator',
          'compressor',
          'lathe',
          'welder',
          'drill press',
          'heavy equipment',
        ],
      },
      {
        value: 'business-office',
        label: 'Office & Commercial Furniture',
        keywords: [
          'filing cabinet',
          'office desk',
          'conference table',
          'cubicle',
          'commercial printer',
          'server rack',
          'point of sale system',
          'safe',
          'shredder',
          'retail display',
        ],
      },
      {
        value: 'restaurant-equipment',
        label: 'Restaurant & Food Service',
        keywords: [
          'commercial fridge',
          'ice machine',
          'fryer',
          'pizza oven',
          'espresso machine',
          'stainless steel table',
          'food truck equipment',
          'catering supplies',
          'commercial kitchen',
        ],
      },
      {
        value: 'containers-bulk',
        label: 'Containers & Bulk Storage',
        keywords: [
          'shipping container',
          'storage unit',
          'pallet',
          'crate',
          'barrel',
          'drum',
          'ibc tote',
          'bulk storage tank',
          'metal shelving',
          'warehouse racking',
        ],
      },
      {
        value: 'farming-equipment',
        label: 'Farming & Agriculture',
        keywords: [
          'tillage equipment',
          'planter',
          'harvester',
          'irrigation system',
          'fertilizer spreader',
          'farm implement',
          'hay bailer',
          'livestock equipment',
          'fencing material',
          'dairy equipment',
        ],
      },
      {
        value: 'scrap-metal-bulk',
        label: 'Scrap & Salvage Material',
        keywords: [
          'scrap metal',
          'reclaimed wood',
          'pallet (sale)',
          'bulk material',
          'salvage item',
          'metal offcuts',
          'plastic sheeting',
          'utility goods',
        ],
      },
    ],
  },
  {
    value: 'Media, Music & Software',
    label: 'Media, Music & Software',
    children: [
      {
        value: 'video-movies',
        label: 'Movies & TV Shows (Physical)',
        keywords: [
          'dvd',
          'blu-ray',
          'vhs',
          '4k uhd disc',
          'film collection',
          'movie box set',
          'physical media',
        ],
      },
      {
        value: 'music-albums',
        label: 'Music (CDs, Vinyl, Tapes)',
        keywords: [
          'cd',
          'vinyl record',
          'lp',
          'cassette tape',
          'music album',
          'audio recording',
          'single',
          'dj vinyl',
          'turntable disc',
        ],
      },
      {
        value: 'video-games-physical',
        label: 'Video Games (Physical)',
        keywords: [
          'game disc',
          'game cartridge',
          'console game',
          'xbox game',
          'playstation game',
          'nintendo game',
          'physical game media',
        ],
      },
      {
        value: 'computer-software-box',
        label: 'Boxed Computer Software',
        keywords: [
          'physical software box',
          'boxed video game',
          'vintage software',
          'computer program (boxed)',
        ],
      },
    ],
  },
  {
    value: 'Hobbies & Recreation',
    label: 'Hobbies & Recreation',
    children: [
      {
        value: 'model-trains-rc',
        label: 'Models, RC & Drones',
        keywords: [
          'model train',
          'rc car',
          'remote control plane',
          'drone (hobbyist)',
          'model kit',
          'plastic model',
          'diecast car',
          'hobby glue',
          'miniature figures',
        ],
      },
      {
        value: 'science-nature-hobby',
        label: 'Science & Nature Hobbies',
        keywords: [
          'telescope',
          'microscope (hobby)',
          'binoculars',
          'rock tumbler',
          'metal detector',
          'amateur radio',
          'ham radio equipment',
          'weather station',
          'chemistry set',
        ],
      },
      {
        value: 'fishing-hunting',
        label: 'Fishing & Hunting Gear',
        keywords: [
          'fishing rod',
          'reel',
          'tackle box',
          'bait',
          'waders',
          'hunting rifle',
          'shotgun',
          'archery bow',
          'tree stand',
          'decoys',
          'firearms accessory',
        ],
      },
      {
        value: 'maternity-infant-care',
        label: 'Maternity & Infant Essentials',
        keywords: [
          'maternity wear',
          'nursing bra',
          'breast pump',
          'baby formula',
          'diapering supplies',
          'prenatal vitamins',
          'infant feeding supplies',
          'baby swing',
          'bouncer seat',
        ],
      },
      {
        value: 'travel-luggage',
        label: 'Travel & Luggage',
        keywords: [
          'suitcase',
          'carry-on bag',
          'duffel bag',
          'travel pack',
          'backpacking gear',
          'luggage set',
          'travel accessories',
        ],
      },
      {
        value: 'camping-outdoor',
        label: 'Camping & Outdoor Gear',
        keywords: [
          'hiking gear',
          'camping tent',
          'sleeping bag',
          'backpacking stove',
          'camping equipment',
          'outdoor sport',
        ],
      },
    ],
  },
  {
    value: 'Real Estate & Property',
    label: 'Real Estate & Property',
    children: [
      {
        value: 'Apartments & Homes for Sale',
        label: 'Apartments & Homes for Sale',
        keywords: [
          'house for sale',
          'apartment for sale',
          'condo',
          'townhouse',
          'villa',
          'property for sale',
          'single-family home',
          'multi-family home',
          'real estate listing',
          'residential property',
        ],
      },
      {
        value: 'Apartments & Homes for Rent',
        label: 'Apartments & Homes for Rent',
        keywords: [
          'apartment for rent',
          'house for rent',
          'rental property',
          'room for rent',
          'lease',
          'short-term rental',
          'long-term rental',
          'furnished rental',
          'unfurnished rental',
        ],
      },
      {
        value: 'Commercial & Office Space',
        label: 'Commercial & Office Space',
        keywords: [
          'office space',
          'retail space',
          'warehouse',
          'commercial property',
          'industrial building',
          'storefront',
          'shop space',
          'land for commercial use',
          'business property',
        ],
      },
      {
        value: 'Land & Plots',
        label: 'Land & Plots',
        keywords: [
          'land for sale',
          'vacant lot',
          'acreage',
          'residential land',
          'commercial land',
          'farm land',
          'plot',
          'real estate lot',
          'undeveloped property',
        ],
      },
    ],
  },
  {
    value: 'Others',
    label: 'Others',
    children: [
      {
        value: 'Pet Supplies',
        label: 'Pet Supplies',
        keywords: [
          'pet food',
          'dog collar',
          'cat litter',
          'aquarium',
          'terrarium',
          'pet toy',
          'leash',
          'harness',
          'pet bed',
          'bird cage',
          'animal care',
          'dog food',
          'fish tank',
          'pet supplies',
        ],
      },
      {
        value: 'Sports Equipment',
        label: 'Sports Equipment',
        keywords: [
          'ball',
          'bat',
          'racket',
          'dumbbell',
          'treadmill',
          'yoga mat',
          'soccer ball',
          'basketball',
          'golf clubs',
          'tennis racket',
          'sports gear',
          'exercise equipment',
          'fitness machine',
          'gym equipment',
          'athletic gear',
        ],
      },
      {
        value: 'Tools-Hardware-DIY',
        label: 'Tools, Hardware & DIY',
        keywords: [
          'tool',
          'drill',
          'saw',
          'hammer',
          'wrench',
          'screwdriver',
          'ladder',
          'tape measure',
          'plumbing parts',
          'electrical fittings',
          'nails',
          'screws',
          'construction material',
          'building supplies',
          'paint (hardware)',
          'lumber',
        ],
      },
      {
        value: 'Collectibles & Antiques',
        label: 'Collectibles & Antiques',
        keywords: [
          'antique',
          'collectible',
          'vintage item',
          'artifact',
          'old object',
          'rare item',
          'memorabilia',
          'stamps',
          'coins',
          'comic books',
          'trading cards',
          'relic',
          'historical item',
        ],
      },
      {
        value: 'non-perishables',
        label: 'Non-Perishable Food & Drink',
        keywords: [
          'canned goods',
          'bottled drinks',
          'unopened food',
          'artisanal sauces',
          'specialty tea',
          'coffee beans',
          'home brewing kit',
          'wine making supplies',
          'non-expired food',
          'bulk food',
        ],
      },
    ],
  },
]
