import logo from "./logo.svg";
import "./App.css";
import AddDress from "./pages/AddDress";
import Layout from "./pages/Layout";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Home from "./pages/Home";
import { Amplify } from "aws-amplify";
import awsconfig from "./aws-exports"; // This file is auto-generated by Amplify
import { withAuthenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import Details from "./pages/Details";
import Chat from "./pages/Chat";
import ChatPage from "./pages/ChatPage";
import Ads from "./pages/Ads";
import Contact from "./pages/Contact";
import Favourites from "./pages/Favourite";

// Configure Amplify
Amplify.configure(awsconfig);
function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Layout />}>
          <Route index element={<Home />} />
          <Route path="addProduct" element={<AddDress />} />
          <Route path="details" element={<Details />} />
          <Route path="chat" element={<Chat />} />
          <Route path="chatPage" element={<ChatPage />} />
          <Route path="ads" element={<Ads />} />
          <Route path="contact" element={<Contact />} />
          <Route path="favourite" element={<Favourites />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

export default withAuthenticator(App);
