/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_identity_pool_id:
    "ap-south-1:c5eaecb0-95a5-4fd0-b5e9-8a0ab0f52bc2",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_R9wR17tT5",
  aws_user_pools_web_client_id: "7jeltl9uu4apdfugbmo1cub7ti",
  oauth: {
    domain: "reusifia5121928-a5121928-dev.auth.ap-south-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: ["http://localhost:3000/", "https://reusifi.com"],
    redirectSignOut: ["http://localhost:3000/", "https://reusifi.com"],
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: ["GOOGLE"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
